sudo : required
node_js:
  - "11.10.1"
services:
  - docker

before_install:
  - docker build -t arghajeet/docker-webreact -f Dockerfile.dev .

script:
  - docker run arghajeet/docker-webreact npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-webreact"
  env: "DockerWebreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-146290068435"
  bucket_path: "docker-webreact"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"